/**
 * bgprocedural.c - W1: build a room in memory instead of loading it from a bg file.
 *
 * The stock path is three phases, and this file replaces all three for stages listed
 * in bgIsProceduralStage():
 *
 *   1. bgReset        loads bg sections 1+2 -> g_BgRooms, g_BgPortals, roomcount
 *   2. bgBuildTables  reads section 3       -> per-room bbox, gfxdatalen, lights
 *   3. bgLoadRoom     streams per-room gfx  -> roomgfxdata, roomblocks, display lists
 *
 * Everything here is additive: bg.c gains three early-out branches and nothing else.
 * The contract this is written against is documented (with file:line evidence) in
 * ../../docs/w1-engine-contract.md. The three facts that matter most:
 *
 *   - ROOM 0 IS A SENTINEL. bg.c:1621 counts rooms from index 1 and bg.c:841/2800/3319
 *     reject roomnum 0. One usable room therefore means roomcount = 2, box at index 1.
 *   - Vertices are ROOM-RELATIVE to g_BgRooms[r].pos, and the room bbox is world space.
 *   - Room display lists address vertices through GBI SEGMENTS, not pointers.
 *     bgRenderRoomPass binds SPSEGMENT_BG_VTX/COL to the block's arrays immediately
 *     before running the list (bg.c:3231), and bgPopulateVtxBatchType reads G_VTX
 *     payloads back as byte offsets into them (bg.c:3369). Emitting a real pointer
 *     here produces garbage vertex batches and broken culling while looking correct.
 */
#include <ultra64.h>
#include "constants.h"
#include "game/bg.h"
#include "game/bgprocedural.h"
#include "bss.h"
#include "data.h"
#include "types.h"
#include "gbiex.h"
#include "lib/memp.h"

#ifndef PLATFORM_N64
#include "system.h"
#endif

/**
 * The level, as generated by tools/mklevel/mklevel.py from campaign/box01.json.
 *
 * Included at FILE SCOPE because the content is large static data and cannot live inside a
 * function body. Generated symbols carry the level id (level_box01_*), because these files
 * are included together and unprefixed names would collide the moment a second level exists.
 *
 * Regenerate with scripts/gen-level.ps1 BEFORE building. The generated file is committed so
 * a clean checkout builds without running the transpiler first, but it is derived data: edit
 * the level description, never this.
 */
#include "generated/box01_geom.inc.c"

#define PROC_LEVEL_ROOMS    level_box01_rooms
#define PROC_LEVEL_NUMROOMS LEVEL_BOX01_NUMROOMS

#define PROC_ROOM        1     // the box. room 0 is the engine's sentinel.

/**
 * Two rooms: the sentinel at 0, and the box at 1.
 *
 * This was 256 for as long as the stage still loaded DEFECTION'S SETUP alongside our
 * geometry. That setup creates props and chrs carrying the original level's room numbers,
 * and Defection has 168 rooms, so a roomcount of 2 sent setupCreateProps indexing g_Rooms
 * far out of bounds -- an access violation inside lvReset, nowhere near the procedural
 * code and easy to misread as a geometry bug. The oversized table was scaffolding around
 * that, with rooms 2..255 degenerate and parked outside the world.
 *
 * setupprocedural.c removed the cause: the setup is ours now and references no room but
 * this one, so the scaffolding goes with it.
 *
 * This value must stay in step with the level description's roomcount, which sizes the
 * TILES room table (mklevel.py emits one entry per room, and collision is looked up per
 * room at collision.c:989). An engine table of 2 against a tiles table sized for Defection
 * does not error: the extra rooms simply read as "no floor".
 */
#define PROC_ROOMCOUNT   LEVEL_BOX01_ROOMCOUNT

// Somewhere no player or prop will ever be.
#define PROC_VOID_COORD  (-1000000.0f)

// Vertex colours are not authored: the level description says nothing about them, and W1
// is deliberately untextured, so the palette lives here and cycles over however many
// vertices the generated room has.
#define PROC_NUMCOLS     8

// One gSPVertex can address at most 16 vertices, so a room with more needs the display
// list split into batches. Nothing does that yet, and a room that silently rendered its
// first 16 vertices would look like a geometry bug rather than a missing feature.
#define PROC_MAXVERTS_PER_BATCH 16
// 12 faces' worth of triangles, each emitted TWICE with opposite winding.
// A room is viewed from the INSIDE, and the first version of this was visible from
// the intro cutscene camera (outside the box) but rendered BLACK from the player's
// position inside it -- the signature of backface culling. gSPClearGeometryMode
// (G_CULL_BOTH) is emitted below and should already prevent that, but double-sided
// geometry removes the question entirely rather than trusting the mode survives the
// port's GBI translation layer. Cost is 12 extra triangles in one room.

// Fixed display-list overhead: 8 state commands, colour, vertex, pipesync, end.
#define PROC_GFX_OVERHEAD 12

// Distinct per-vertex colours: makes it unmistakable that what is on screen is OUR
// geometry and not a surviving piece of the original level. Cycles when a room has more
// vertices than there are entries.
static const u32 g_ProcPalette[PROC_NUMCOLS] = {
	0xff3050ff, 0xff30ff50, 0xffff5030, 0xffffe030,
	0xff9030ff, 0xff30e0ff, 0xffff30a0, 0xffe0e0e0,
};

/**
 * The generated room for a room number, or NULL if that room has no authored geometry.
 */
static const struct procroom *procFindRoom(s32 roomnum)
{
	s32 i;

	for (i = 0; i < PROC_LEVEL_NUMROOMS; i++) {
		if (PROC_LEVEL_ROOMS[i]->index == roomnum) {
			return PROC_LEVEL_ROOMS[i];
		}
	}

	return NULL;
}


// Defined in bg.c but not exposed through a header.
extern struct bgcmd *g_BgCommands;
extern f32 *g_BgStanThings;

static struct bgroom *g_ProcBgRooms;
static struct bgportal *g_ProcBgPortals;

bool bgIsProceduralStage(s32 stagenum)
{
	return stagenum == STAGE_DEFECTION;
}

/**
 * Phase 1: stand in for the section 1 + 2 load.
 *
 * Produces the same globals bgReset would have produced: a bgroom array indexed from
 * 1 and terminated by a zero unk00, an empty portal table, and no commands, lights or
 * stan data.
 */
void bgProceduralReset(s32 stagenum)
{
	s32 i;

	// bgroom array: [0] sentinel, [1] the box, [2] terminator (unk00 == 0 ends the
	// count loop at bg.c:1623).
	g_ProcBgRooms = mempAlloc(ALIGN16((PROC_ROOMCOUNT + 1) * sizeof(struct bgroom)), MEMPOOL_STAGE);

	for (i = 0; i < PROC_ROOMCOUNT + 1; i++) {
		g_ProcBgRooms[i].unk00 = 0;
		g_ProcBgRooms[i].pos.x = 0.0f;
		g_ProcBgRooms[i].pos.y = 0.0f;
		g_ProcBgRooms[i].pos.z = 0.0f;
		g_ProcBgRooms[i].br_light_min = 255;
		g_ProcBgRooms[i].br_light_max = 255;
	}

	// Non-zero marks an entry as a real room for the counting loop at bg.c:1623, which
	// stops at the first zero unk00. The stock value is a segment address into the bg
	// file; nothing dereferences it on this path.
	for (i = 1; i < PROC_ROOMCOUNT; i++) {
		g_ProcBgRooms[i].unk00 = 1;
		g_ProcBgRooms[i].pos.x = PROC_VOID_COORD;
		g_ProcBgRooms[i].pos.y = PROC_VOID_COORD;
		g_ProcBgRooms[i].pos.z = PROC_VOID_COORD;
	}

	for (i = 0; i < PROC_LEVEL_NUMROOMS; i++) {
		const struct procroom *pr = PROC_LEVEL_ROOMS[i];

		g_ProcBgRooms[pr->index].pos.x = pr->origin[0];
		g_ProcBgRooms[pr->index].pos.y = pr->origin[1];
		g_ProcBgRooms[pr->index].pos.z = pr->origin[2];
	}

	// Terminator.
	g_ProcBgRooms[PROC_ROOMCOUNT].unk00 = 0;

	// Empty portal table: a single terminator (verticesoffset == 0 ends every portal
	// loop, e.g. bg.c:1719 and bg.c:2037).
	g_ProcBgPortals = mempAlloc(ALIGN16(2 * sizeof(struct bgportal)), MEMPOOL_STAGE);
	g_ProcBgPortals[0].verticesoffset = 0;
	g_ProcBgPortals[0].roomnum1 = 0;
	g_ProcBgPortals[0].roomnum2 = 0;
	g_ProcBgPortals[0].flags = 0;
	g_ProcBgPortals[1] = g_ProcBgPortals[0];

	g_BgRooms = g_ProcBgRooms;
	g_BgPortals = g_ProcBgPortals;
	g_BgCommands = NULL;
	g_BgLightsFileData = NULL;
	g_BgStanThings = NULL;

	g_Vars.roomcount = PROC_ROOMCOUNT;

#ifndef PLATFORM_N64
	sysLogPrintf(LOG_NOTE, "bgprocedural: stage 0x%02x reset, roomcount=%d, room %d origin (%.1f, %.1f, %.1f)",
			stagenum, (s32)g_Vars.roomcount, PROC_ROOM,
			g_ProcBgRooms[PROC_ROOM].pos.x,
			g_ProcBgRooms[PROC_ROOM].pos.y,
			g_ProcBgRooms[PROC_ROOM].pos.z);
#endif
}

/**
 * Phase 2: stand in for the section 3 read inside bgBuildTables.
 *
 * Section 3 supplies, per room: the bounding box (as s16 offsets from the room origin),
 * the gfxdata length, and the light count. Mirrors bg.c:1957-2008 including the centre
 * and radius derivations, so the numbers are computed the same way rather than guessed.
 */
void bgProceduralBuildRoomMetrics(void)
{
	s32 r;

	for (r = 1; r < g_Vars.roomcount; r++) {
		const struct procroom *pr = procFindRoom(r);

		if (pr != NULL) {
			g_Rooms[r].bbmin[0] = pr->bbmin[0];
			g_Rooms[r].bbmin[1] = pr->bbmin[1];
			g_Rooms[r].bbmin[2] = pr->bbmin[2];
			g_Rooms[r].bbmax[0] = pr->bbmax[0];
			g_Rooms[r].bbmax[1] = pr->bbmax[1];
			g_Rooms[r].bbmax[2] = pr->bbmax[2];
		} else {
			// Degenerate filler so the surviving original setup can reference any
			// room number without indexing out of bounds. Parked far away so it is
			// never visible and never contains the player.
			g_Rooms[r].bbmin[0] = PROC_VOID_COORD;
			g_Rooms[r].bbmin[1] = PROC_VOID_COORD;
			g_Rooms[r].bbmin[2] = PROC_VOID_COORD;
			g_Rooms[r].bbmax[0] = PROC_VOID_COORD + 1.0f;
			g_Rooms[r].bbmax[1] = PROC_VOID_COORD + 1.0f;
			g_Rooms[r].bbmax[2] = PROC_VOID_COORD + 1.0f;
		}

		g_Rooms[r].centre.x = (g_Rooms[r].bbmin[0] + g_Rooms[r].bbmax[0]) / 2.0f;
		g_Rooms[r].centre.y = (g_Rooms[r].bbmin[1] + g_Rooms[r].bbmax[1]) / 2.0f;
		g_Rooms[r].centre.z = (g_Rooms[r].bbmin[2] + g_Rooms[r].bbmax[2]) / 2.0f;

		g_Rooms[r].radius = sqrtf(
				(g_Rooms[r].bbmin[0] - g_Rooms[r].bbmax[0]) * (g_Rooms[r].bbmin[0] - g_Rooms[r].bbmax[0])
				+ (g_Rooms[r].bbmin[1] - g_Rooms[r].bbmax[1]) * (g_Rooms[r].bbmin[1] - g_Rooms[r].bbmax[1])
				+ (g_Rooms[r].bbmin[2] - g_Rooms[r].bbmax[2]) * (g_Rooms[r].bbmin[2] - g_Rooms[r].bbmax[2])) / 2.0f;

		// Any non-zero length; the procedural loader does not stream, so this is only
		// used for allocation sizing decisions elsewhere.
		g_Rooms[r].gfxdatalen = 4096;

		// Explicit: only the box ever has geometry. bgBuildTables already nulls these
		// (bg.c:1919) but something on this path was observed writing a garbage
		// pointer into unloaded rooms' gfxdata afterwards, so re-assert it here.
		if (r != PROC_ROOM) {
			g_Rooms[r].gfxdata = NULL;
			g_Rooms[r].loaded240 = 0;
		}

		// No lights in W1. lightindex -1 is how the stock loader marks "no lights"
		// (bg.c:2004), and it keeps g_Rooms[r].colours NULL so bgRenderRoomPass uses
		// block->colours unchanged (bg.c:3245).
		g_Rooms[r].numlights = 0;
		g_Rooms[r].lightindex = -1;
	}
}

/**
 * Phase 3: stand in for bgLoadRoom's streamed geometry.
 *
 * Allocation layout deliberately mirrors the file layout the engine expects, which was
 * read off the reference dump's pointer arithmetic (gfxdata + 0x28 = opablock,
 * + 0x28 = xlublock, + 0x28 = vertices) and is assumed by bg.c:3242
 * (addr = ALIGN8(&gfxdata->vertices[numvertices]) for the colour base):
 *
 *   [roomgfxdata header][block 0][block 1][vertices][colours][display list]
 */
void bgProceduralLoadRoom(s32 roomnum)
{
	u8 *buf;
	struct roomgfxdata *g;
	struct roomblock *opa;
	Vtx *verts;
	Col *cols;
	Gfx *gdl;
	Gfx *gdlstart;
	u32 total;
	s32 i;

	const struct procroom *pr;

	pr = procFindRoom(roomnum);

	if (pr == NULL) {
		return;
	}

	// A room whose vertices cannot all be addressed by one gSPVertex would render its
	// first 16 and silently drop the rest, which reads as a geometry bug. Refuse loudly
	// instead; batching is the fix when a level actually needs it.
	if (pr->numverts > PROC_MAXVERTS_PER_BATCH) {
#ifndef PLATFORM_N64
		sysLogPrintf(LOG_ERROR,
				"bgprocedural: room %d has %d verts, over the %d addressable by one gSPVertex",
				roomnum, pr->numverts, PROC_MAXVERTS_PER_BATCH);
#endif
		return;
	}

	if (g_Rooms[roomnum].gfxdata != NULL) {
		g_Rooms[roomnum].loaded240 = 1;
		return;
	}

	total = sizeof(struct roomgfxdata)
			+ sizeof(struct roomblock) * 2
			+ sizeof(Vtx) * pr->numverts + 8
			+ sizeof(Col) * PROC_NUMCOLS + 8
			+ sizeof(Gfx) * (PROC_GFX_OVERHEAD + (pr->numtris + 3) / 4) + 8;

	buf = sysMemAlloc(total);

	if (buf == NULL) {
#ifndef PLATFORM_N64
		sysLogPrintf(LOG_ERROR, "bgprocedural: failed to alloc %u bytes for room %d", total, roomnum);
#endif
		return;
	}

	g = (struct roomgfxdata *)buf;
	opa = &g->blocks[0];
	verts = (Vtx *)ALIGN8((uintptr_t)&g->blocks[2]);
	cols = (Col *)ALIGN8((uintptr_t)&verts[pr->numverts]);
	gdl = (Gfx *)ALIGN8((uintptr_t)&cols[PROC_NUMCOLS]);
	gdlstart = gdl;

	// The generated vertices are ALREADY room-relative, so they are copied straight in.
	// The old hardcoded path derived them here by subtracting the room origin from world
	// bounds; doing that again would offset them twice.
	for (i = 0; i < pr->numverts; i++) {
		verts[i].x = pr->vertices[i].x;
		verts[i].y = pr->vertices[i].y;
		verts[i].z = pr->vertices[i].z;
		verts[i].flags = 0;
		// BYTE offset into the colour segment, not an index (bgAddXrayTri: i << 2).
		verts[i].colour = (u8)(i << 2);
		verts[i].s = 0;
		verts[i].t = 0;
	}

	for (i = 0; i < PROC_NUMCOLS; i++) {
		cols[i].word = PD_BE32(g_ProcPalette[i % PROC_NUMCOLS]);
	}

	// --- display list ---
	// Untextured, vertex-coloured, no culling, z-buffered opaque.
	gDPPipeSync(gdl++);
	gSPClearGeometryMode(gdl++, G_CULL_BOTH | G_LIGHTING | G_TEXTURE_GEN | G_FOG);
	gSPSetGeometryMode(gdl++, G_ZBUFFER | G_SHADE | G_SHADING_SMOOTH);
	gDPSetCycleType(gdl++, G_CYC_1CYCLE);
	gDPSetTextureLUT(gdl++, G_TT_NONE);
	gSPTexture(gdl++, 0, 0, 0, G_TX_RENDERTILE, G_OFF);
	gDPSetCombineMode(gdl++, G_CC_SHADE, G_CC_SHADE);
	gDPSetRenderMode(gdl++, G_RM_AA_ZB_OPA_SURF, G_RM_AA_ZB_OPA_SURF2);

	// SEGMENTED addresses, and they MUST be marked with SEGADDR (bit 0 set).
	// fast3d's seg_addr() only resolves against the segment table when the low bit is
	// set, and otherwise uses the word AS A RAW POINTER (gfx_pc.cpp:2262). Passing a
	// bare (segment << 24) therefore hands the renderer 0x0e000000 to dereference,
	// which is exactly how this first failed. The offset field is masked 0x00fffffe,
	// so segment-relative offsets must also be even.
	gSPColor(gdl++, SEGADDR(SPSEGMENT_BG_COL << 24), PROC_NUMCOLS);
	gSPVertex(gdl++, SEGADDR(SPSEGMENT_BG_VTX << 24), pr->numverts, 0);

	// gSPTri4 always emits four triangles, so a count that is not a multiple of four is
	// padded by repeating the last triangle. Degenerate padding would be cheaper, but a
	// repeat is harmless here and needs no special index.
	for (i = 0; i < pr->numtris; i += 4) {
		s32 a = i + 1 < pr->numtris ? i + 1 : pr->numtris - 1;
		s32 b = i + 2 < pr->numtris ? i + 2 : pr->numtris - 1;
		s32 c = i + 3 < pr->numtris ? i + 3 : pr->numtris - 1;

		gSPTri4(gdl++,
				pr->tris[i][0], pr->tris[i][1], pr->tris[i][2],
				pr->tris[a][0], pr->tris[a][1], pr->tris[a][2],
				pr->tris[b][0], pr->tris[b][1], pr->tris[b][2],
				pr->tris[c][0], pr->tris[c][1], pr->tris[c][2]);
	}

	gDPPipeSync(gdl++);
	gSPEndDisplayList(gdl++);

	opa->type = ROOMBLOCKTYPE_LEAF;
	opa->next = NULL;
	opa->gdl = gdlstart;
	opa->vertices = verts;
	opa->colours = cols;

	g->vertices = verts;
	g->colours = cols;
	g->opablocks = opa;
	g->xlublocks = NULL;   // nothing translucent in W1
	g->lightsindex = -1;
	g->numlights = 0;
	g->numvertices = pr->numverts;
	g->numcolours = PROC_NUMCOLS;

	g_Rooms[roomnum].gfxdata = g;
	g_Rooms[roomnum].loaded240 = 1;

#ifndef PLATFORM_N64
	sysLogPrintf(LOG_NOTE, "bgprocedural: built room %d, %d verts %d tris, gdl %d cmds, %u bytes",
			roomnum, pr->numverts, pr->numtris, (s32)(gdl - gdlstart), total);
#endif
}

/*
 * bgProceduralKeepRoomLoaded() used to live here and made procedural rooms permanently
 * resident. It is GONE deliberately: skipping bgUnloadRoom also skipped the frees that
 * NULL vtxbatches and gfxdata, which crashed the game on level restart. See the note in
 * bgUnloadRoom. Rooms are rebuilt on demand instead, which is what bgLoadRoom's
 * interception already provides.
 */
